### PR TITLE
Add a Cargo.toml so that this grammar can be used as a Rust crate

### PR DESCRIPTION
**Pull request by nokome**
This simplifies usage a great deal when integrating into a Rust project. The `Cargo.toml` is based heavily on https://github.com/tree-sitter/tree-sitter-python/blob/master/Cargo.toml.

Ideally this would be published on crates.io along side `tree-sitter-python`, `tree-sitter-javascript` etc. I'd be happy to assist with that if so desired.

### CODE REVIEW

**Comment by nokome** [comment]
I apologize in advance if this is unnecessary noise, but it would be nice if this PR could get some attention.

We are currently using it in production to incorporate `tree-sitter-r` into an Rust project: https://github.com/stencila/stencila/blob/96efd26e61a28a295cffc0f56079e58f3c252a1b/rust/Cargo.toml#L232. I'd like to be able to replace that fork URL, with the URL for this repo and, to reiterate, am happy to help publish to crates.io, which would be even better.

**Comment by jimhester** [comment]
Sorry for the delay, it looks fine, thank you for submitting the PR!

**Comment by jimhester** [comment]
Ok it is also now published on crates.io (https://crates.io/crates/tree-sitter-r)

Pretty nice process :)

**Comment by nokome** [comment]
Great, thank you!

**Pull request merged**
