### PR TITLE
Update bindings, tests, scanner, and workflows

### PR DESCRIPTION
**Pull request by ObserverOfTime**
The publish workflow requires a `crates` environment with a `CARGO_REGISTRY_TOKEN` secret.
Node and Python packages can also be published but are currently commented out.

The version should be bumped to (at least) `0.21.0` in these files before publishing:
- Cargo.toml
- Makefile
- package.json
- pyproject.toml
- bindings/r/DESCRIPTION

You should also run `npm i` and `cargo build` to update the lockfiles.

### CODE REVIEW

**Comment by ObserverOfTime** [comment]
The `-pedantic` warning will be fixed in the next cli release.

```
parser.c:380064:73: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
380064 |   [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0),
```

 I can regenerate the parser with the master cli build if you want.

**Comment by ObserverOfTime** [comment]
```
 ❯ checking compilation flags in Makevars ... WARNING
  Non-portable flags in variable 'PKG_CFLAGS':
    -std=c11

❯ checking pragmas in C/C++ headers and code ... NOTE
  Files which contain pragma(s) suppressing diagnostics:
    ‘src/parser.c’ ‘src/tree_sitter/array.h’

0 errors ✔ | 1 warning ✖ | 1 note ✖
Error: Error: R CMD check found WARNINGs
Execution halted
Error: Process completed with exit code 1.
```
@DavisVaughan Is there another way to force C11?

**Comment by DavisVaughan** [comment]
I greatly appreciate the work here, but I will likely take this and split it up into a few smaller PRs, just so I can fully understand all the changes. We haven't been quite ready to update to the latest tree-sitter yet, but it is on my short list of things to do, and then it will be easier to incrementally look at these changes, as updating seems to create quite a few new files / bindings / etc.

Regarding C11, you can probably use `SystemRequirements: C11` but we haven't actually done very much testing of C11 support in the tidyverse / r-lib R packages, so we aren't quite sure how widely supported that is in R. I guess it is absolutely required by tree-sitter?

Again, we really do appreciate what you are doing here! And this work will definitely get pulled in, just in smaller chunks at a time as I work through it myself.

**Comment by ObserverOfTime** [comment]
> I guess it is absolutely required by tree-sitter?

It needs at least C11. The default is _usually_ C17 (it is in R too) but we explicitly set it just in case.

**Pull request closed without merging**
