### PR TITLE
Add fields to 'unary' and 'binary' rules.

### PR DESCRIPTION
**Pull request by echasnovski**
This PR addresses small inconsistency between tree-sitter grammars for R and other languages. It relates to how unary and binary operations are parsed.

Currently only special operator is parsed as [named node](https://tree-sitter.github.io/tree-sitter/using-parsers#named-vs-anonymous-nodes). This seems to eliminate the possibility of making queries which depend on operator: for example, I couldn't find a way to make a query for binary formula (`a ~ b`).

This PR is basically an adaptation from other languages (like [Python](https://github.com/tree-sitter/tree-sitter-python/blob/3196e288650992bca2399dda15ac703c342a22bb/grammar.js#L590), [Rust](https://github.com/tree-sitter/tree-sitter-rust/blob/2beedf23bedbd7b02b416518693e8eed3944d4a0/grammar.js#L939), [JavaScript](https://github.com/tree-sitter/tree-sitter-javascript/blob/3d906f36a62e4cf165f5baa9626db905584d9752/grammar.js#L736)). It makes parts of parsed binary and unary operations to be fields. This enables queries for formula to be `(binary operator: "~") @formula`.

Couple of questions:

- In most languages rules for unary and binary operators are not called simply 'unary' and 'binary'. What do you think about renaming them for more consistency (although there isn't much to begin with)? Some options: 'binary_expression' (seems to be most common), 'binary_operator', 'binary_operation'.
- Names for parts of binary operator seem to be consistent across languages: 'left', 'operator', 'right'. For unary operator not so much. What are your thoughts on names chosen in this PR ('operator', 'operand')? They were chosen from Ruby which also has 'binary' and 'unary' names. Other common choice is 'operator', 'argument'.

If these changes are OK, I'll update tests and other necessary files.

### CODE REVIEW

**Comment by jimhester** [comment]
Thanks! I think your changes sound good, thank you! If you could update the tests to include the new names that would be great, thanks!

**Comment by echasnovski** [comment]
Just to be sure: don't touch rule names ("binary" and "unary") and accept proposed field names of unary rule ("operator" and "operator")?

**Comment by jimhester** [comment]
yes, exactly

**Comment by echasnovski** [comment]
Updated tests (with slight reformatting on those tests which were affected) and ran `tree-sitter generate`.

**Comment by jimhester** [comment]
Great thanks again!

**Pull request merged**
