### PR TITLE
Rename nodes to avoid usage of special characters

### LINKED ISSUE #62: "..i" node name gives problems with tree-sitter-node
The `..i` token defined here: https://github.com/r-lib/tree-sitter-r/blob/1e9eaa9af98c9ac92e3d1e1713a453eef488fe36/grammar.js#L304

Causes an error when this parser is loaded in `tree-sitter-node`, because it creates a class for each syntax node and a dot (`.`) is illegal in a class name.

Is it possible to use a different name (without special characters) for this token?

### PR DESCRIPTION
**Pull request by rien**
This PR renames nodes in the grammar which used special characters (operators, brackets, ...). These nodes would give errors when the parse was loaded with the Node.js bindings for tree-sitter. (The bindings try to create a class with the node name, but since special characters are not allowed, it fails with a `SyntaxError: Unexpected token '?'`). 

I've used the [R source code](https://github.com/wch/r-source/blob/trunk/src/main/gram.y) and [language reference](https://cran.r-project.org/doc/manuals/r-release/R-lang.html) to pick names. I am not very familiar with R, so better names are probably possible. Feel free to suggest alternatives!

I confirm that with these new names, the Node.js bindings work, so this PR fixes #62.

### CODE REVIEW

**Comment by kevinushey** [comment]
Thanks for the PR! I don't like the idea of needing to change the names of all entities in the grammar, though. Is there any chance that the Node.js bindings themselves (or how they're generated) could be patched to accommodate the names we've chosen?

As an aside, what's the easiest way for me to reproduce locally the problem you're seeing?

**Comment by rien** [comment]
@kevinushey do you have any input on how you want to fix this? I quite agree with the comment of @amaanq in https://github.com/tree-sitter/node-tree-sitter/issues/173. This grammar is probably a bit too detailed, would it make sense to make some of the rules more abstract?

I don't want to impose however -- if you would like to leave this grammar as-is, that is completely fine. I will probably make some local changes for the project where I need it.

**Comment by kevinushey** [comment]
I think I've come around, especially after @DavisVaughan has also banged his head on very similar issues when working with this grammar as well.

I suspect we'll want to rename most of these usages to just plain old "operator" nodes, or "unary_operator" + "binary_operator" nodes.

I'm less sure if we want things like `<-` and `::` to be "special" in the grammar, since as far as the R parser is concerned, they're more-or-less just operators like any other operator.

**Comment by rien** [comment]
Looking at other grammars (like https://github.com/tree-sitter/tree-sitter-python), it seems like they pick something in between. They make the distinction between [`boolean_operator`](https://github.com/tree-sitter/tree-sitter-python/blob/4bfdd9033a2225cc95032ce77066b7aeca9e2efc/grammar.js#L764), [`binary_operator`](https://github.com/tree-sitter/tree-sitter-python/blob/4bfdd9033a2225cc95032ce77066b7aeca9e2efc/grammar.js#L777), [`comparison_operator`](https://github.com/tree-sitter/tree-sitter-python/blob/4bfdd9033a2225cc95032ce77066b7aeca9e2efc/grammar.js#L808), [`assignment`](https://github.com/tree-sitter/tree-sitter-python/blob/4bfdd9033a2225cc95032ce77066b7aeca9e2efc/grammar.js#L843), etc. I think it makes sense to group operators based on what they do and not throw them together in one category.

Feel free to close this PR and/or create a new one based on this work. I will continue with my current fork in our own project for now.

**Pull request closed without merging**
